---
- name: create Xsession.d directory
  become: yes
  file:
    path: "{{ default_web_browser_xsession_d_dir }}"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'

- name: write Xsession config
  become: yes
  template:
    src: x-session.j2
    dest: '{{ default_web_browser_xsession_d_dir }}/80-ansible-default-web-browser'
    owner: root
    group: root
    mode: 'u=rw,go=r'
