---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-default-web-browser-ubuntu-min
    image: ubuntu:16.04
  - name: ansible-role-default-web-browser-ubuntu-max
    image: ubuntu:18.04

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
