---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible-role-default-web-browser-ubuntu-min
    image: ubuntu:16.04
  - name: ansible-role-default-web-browser-ubuntu-max
    image: ubuntu:20.04

provisioner:
  name: ansible

verifier:
  name: testinfra
