---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create applications directory
      become: yes
      file:
        path: "{{ default_web_browser_applications_dir }}"
        state: directory
        owner: root
        group: root
        mode: 'u=rwx,go=rx'

    - name: create desktop file
      become: yes
      copy:
        content: 'Exec=/usr/bin/google-chrome-stable %U'
        dest: "{{ default_web_browser_applications_dir }}/google-chrome.desktop"
        owner: root
        group: root
        mode: 'u=rwx,go=rx'

  roles:
    - ansible-role-default-web-browser
